version: '3.8'
services:

  # 1. Definiamo il servizio BACKEND
  backend:
    build:
      context: ./backend
    ports:
      - "8003:8003"
    volumes:
      - ./gs_data:/app/gs_data
      - ./domains.json:/app/domains.json
      - ./backend/src/parsers/risultati:/app/src/parsers/risultati

  # 2. Definiamo il servizio FRONTEND
  frontend:
    build:
      context: ./frontend
    ports:
      - "8004:8004"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8003