version: '3.8'
services:

  # 1. Definiamo il servizio BACKEND
  backend:
    build:
      context: ./backend
    ports:
      - "8003:8003"
    depends_on:
      - mariadb
      - ollama
    environment:
      - DB_HOST=mariadb
      - DB_USER=minerva_user       # <-- Nuovo utente
      - DB_PASSWORD=minerva_pass 
      - DB_NAME=minerva_db
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - ./gs_data:/app/gs_data
      - ./domains.json:/app/domains.json
      - ./backend/src/parsers/risultati:/app/src/parsers/risultati

  # 2. Definiamo il servizio FRONTEND
  frontend:
    build:
      context: ./frontend
    ports:
      - "8004:8004"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8003

  # 3. Definiamo il database MARIADB
  mariadb:
    image: mariadb:11.7.2-ubi9     
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: minerva_db
      MYSQL_USER: minerva_user     
      MYSQL_PASSWORD: minerva_pass 
    volumes:
      - ./mariadb_data:/var/lib/mysql
      - ./init_db:/docker-entrypoint-initdb.d  
    # Aggiunta del healthcheck per MariaDB per assicurarsi che il servizio sia pronto prima di avviare il backend
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 3. Si definisce il servizio OLLAMA
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - ./ollama_data:/root/.ollama #./ollama_data -> percorso su computer fisico, path relativo alla posizione in cui si trova il file .yaml,
      #/root/.ollama percorso all'interno del file system isolato del container di ollama (docker esige che la destinazione interna 
      #al container sia un path assoluto)
      - ./entrypoint.sh:/entrypoint.sh
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
